### ISSUE TITLE
How to generator a custom model log file for the simrd?

### ISSUE THREAD

**Issue by Sun2018421** [uwsampl/dtr-prototype#15]
Hello, as you mentioned, I can obtain the running log of the model by myself, but I did not find the relevant code under the  simrd folder. May I ask for the introduction? Thank you very much 
![image](https://github.com/uwsampl/dtr-prototype/assets/38587877/ef08cadc-e01e-4f08-8ffa-be07362e5102)

**Comment by MarisaKirisame** [comment]
Hi @Sun2018421 , sorry for the late reply!
The code (CheckpointTensorImpl.cpp) have a few switch that generate log. The log generated could then be fed into simrd.

**Comment by Sun2018421** [comment]
Thank you very much for your response. I have understood the information provided.
